
export enum AppState {
  MANIFESTO = 'MANIFESTO',
  ONBOARDING = 'ONBOARDING',
  DASHBOARD = 'DASHBOARD',
  FLOW_MODE = 'FLOW_MODE',
  BRAIN_DUMP = 'BRAIN_DUMP'
}

export enum TaskPriority {
  CRITICAL = 'CRITICAL', // "Do or die"
  HIGH = 'HIGH',         // "Strategic importance"
  MEDIUM = 'MEDIUM',     // "Maintenance"
  LOW = 'LOW'            // "Someday"
}

export enum EnergyLevel {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  DEPLETED = 'DEPLETED'
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  estimatedDuration: number; // in minutes
  priority: TaskPriority;
  energyCost: 'HIGH' | 'LOW'; // Cognitive load
  deadline?: string;
  category: 'WORK' | 'LEARNING' | 'LIFE';
  status: 'PENDING' | 'COMPLETED' | 'DEFERRED';
  aiResult?: string; // Content generated by AI
  isAiGeneratable?: boolean; // Can AI fully execute this?
  autoExecuteWithAI?: boolean; // Should AI automatically execute this?
  projectId?: string; // Link to a parent project
}

export interface Project {
  id: string;
  title: string;
  description: string;
  progress: number; // 0-100
  status: 'ACTIVE' | 'COMPLETED' | 'ON_HOLD';
  subtasks: Task[]; // Nested tasks
}

export interface UserProfile {
  name: string;
  email: string;
  bio?: string; // "Chemist turned coder"
}

export interface GeminiResponse {
  tasks: Task[];
  analysis: string;
  realityCheck: boolean; // True if schedule is realistic, False if overbooked
}
